services:
  backend:
    build: ./backend
    container_name: SMS-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: sms
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
  
  frontend:
    build: ./frontend
    container_name: SMS-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app       
      - /app/node_modules
    command: npm run dev
  postgres:
    image: postgres:16
    container_name: sms-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 
