version: "3.8"

services:
  backend:
    build: ./backend
    container_name: SMS-backend
    ports:
      - "51888:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/attendance_db"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
  
  frontend:
    build: ./frontend
    container_name: SMS-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_ATTENDANCE_API_URL: "http://localhost:51888"
      VITE_SMS_API_URL: "http://localhost:51888"
    volumes:
      - ./frontend:/app       
      - /app/node_modules
    command: npm run dev -- --host
  postgres:
    image: postgres:16
    container_name: sms-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    volumes:
      - pgdata_sms:/var/lib/postgresql/data
volumes:
  pgdata_sms:
