services:
  backend:
    build: ./backend
    container_name: SMS-backend
    ports:
      - "3000:3000"
    # networks:
    #   - "sms_network"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: sms
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: SMS-frontend
    ports:
      - "5173:5173"
    # networks:
    #   - "sms_network"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:16
    container_name: sms-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  auth-service:
    build: ./auth-service
    container_name: sms-auth-service
    command: npm run start:dev
    ports:
      - "3001:3000"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - ./auth-service/.env

  user-service:
    build: ./user-service
    container_name: sms-user-service
    command: npm run start:dev
    ports:
      - "3002:3000"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - ./user-service/.env
volumes:
  pgdata:

# networks:
#   sms_network:
#     driver: bridge
